# Generated by Django 3.2.15 on 2022-09-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_selling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='prod_price',
            field=models.IntegerField(),
        ),
    ]
