# Generated by Django 3.2.15 on 2022-09-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_selling_prod_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
