# Generated by Django 3.2.15 on 2022-09-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_selling_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='prod_img',
            field=models.FileField(default=' ', upload_to='main/images'),
        ),
    ]
